apiVersion: apps/v1
kind: Deployment
metadata:
  name: zap1
  labels:
    app: zap1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zap1
  template:
    metadata:
      labels:
        app: zap1
    spec:
      containers:
      - name: zap1
        image: owasp/zap2docker-stable
        ports:
        - containerPort: 8080
